name: build/test
on:
  workflow_call:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: benjlevesque/short-sha@v2.1
        id: short-sha
      - name: Set up golang ${{ matrix.go-version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: build
        run: |
          make binary
      - name: lint
        run: |
          make lint
      - name: Upload code coverage
        uses: codecov/codecov-action@v3
      - uses: actions/cache@v3
        id: restore-build
        with:
          path: sbom
          key: ${{ github.sha }}
